name: marcos
favicon: null
layout_spectrum: 0.4062325560953468
typography_spectrum: 0.11915977415628731
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.44873148389160633
  lightness: 0.6850834549404681
  saturation: 0.47962553915567696
  rhythmicContrast: 0.18235469912178814
purpose: []
