name: Marcos Macros
favicon: null
layout_spectrum: 0.75784
typography_spectrum: 0
title: 'Photographer & Vegan in Korea'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c5c6c8'
    - '#a3a5a8'
    - '#2e2c2d'
    - '#535456'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.18235469912178814
purpose: []
